language: php

php: [5.3, 5.4, 5.5, hhvm]

before_script:
  - composer install --dev --prefer-source

script: php test/test.php

after_script:
  - cat clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml
